### ISSUE TITLE
Requires Go 1.15

### ISSUE THREAD

**Issue by moshix** [racingmars/proxy3270#1]
Hello 

This is premium stuff! Thank you! It woks as advertised as long as one has Go 1.15. 

Most distros and Macos brew have a version below 1.15 (my Macos dev system has 1.14). 

It seems the only issues is the use of os.ErrDeadlineExceeded from 1.15. 

I believe it would benefit many people if you could make it also compile with Go 1.13 (which has support for modules) and 1.14. 

many thanks! will definitely become a video

M

**Comment by racingmars** [comment]
Ah... yes, that uses the new error wrapping feature of Go 1.15. Let me go check the older documentation to see how I can check for that error without using the 1.15 version.

**Comment by moshix** [comment]
Yes, saw that. there are some other ways to do error handling in pre-1.15. 

thanks

M
