### ISSUE TITLE
yes, TN3270 closes telnet connection

### ISSUE THREAD

**Issue by moshix** [racingmars/proxy3270#2]
Hello

responding to what you wrote in the README.md where you surmise that tn3270 closes telnet connections. 

Indeed that is the case, when z/OS or z/VM logs off a user, it also closes the telnet connection. That's the protocol for tn3270. 

Many thanks

M

**Comment by racingmars** [comment]
Right -- it's the remote host closing the connection. But that is the connection between proxy3270 and the remote server, so proxy3270 still has the open connection to the client, and I was hoping I could just keep on talking to the client. But I'm guessing there's some telnet/3270 control commands getting the client into a state that I need to either unroll or figure out.

**Comment by moshix** [comment]
Ah ok. that I don't know. 

thanks

M
