### ISSUE TITLE
Forwarding not working

### ISSUE THREAD

**Issue by moshix** [racingmars/proxy3270#3]
Forwarding doesn't seem to work:

23 11:47:38 INF LISTENING ON PORT 12000 FOR CONNECTIONS
23 11:47:38 INF Press Ctrl-C to end server.
23 11:47:42 INF New connection from 99.99.99.99:51663
23 11:47:53 DBG connection closed
23 11:47:53 DBG ending readAndFeed(): client
23 11:47:53 DBG got clientdone
23 11:47:54 DBG server got end signal
23 11:47:54 DBG ending readAndFeed(): server
23 11:48:07 INF New connection from 99.99.99.99:51663

IP changed for obvious reasons

M

**Comment by racingmars** [comment]
Hmm...that's unfortunate! What 3270 emulator are you using? It looks like it's the client closing the connection out of the blue. I've only tested with c3270 so far... perhaps I should run through all the clients I have and see if any give me trouble.

**Comment by moshix** [comment]
It's standard x3270. it has the same problem with all typical terminal sizes.

**Comment by racingmars** [comment]
It seems the telnet "DO" and "WILL" commands aren't idempotent, and depending on the particular 3270 emulator's behavior AND which options the remote server tries to negotiate, clients can get into states they aren't expecting. I have added an "un-negotiate" function to the underlying go3270 library which attempts to get the telnet options state back to the original fresh connection state, and am now calling it from proxy3270 before forwarding the client connection to the remote server.

@moshix, want to give this update a try and see if it starts working for you?

**Comment by moshix** [comment]
Seems to work much better now. I tried:

x3270 works with MVS VM, z/VM and z/OS
c3270 with the same hosts

also, i tried forwarding to a mainframe on a remote internet host and that worked also. 

good job Matt!

**Comment by moshix** [comment]
closing for now. Thanks a lot
