### ISSUE TITLE
Vista3270 get resized to mod2 upon connection to proxy3270

### ISSUE THREAD

**Issue by moshix** [racingmars/proxy3270#5]
I have been trying to get Vista3270 to connect as mod 4 or any other model other than mod2, but upon connection every terminal gets resized to mod2 with proxy3270...

proxy3270 throws the error: coudn't handle screen for..."

thanks

M

**Comment by racingmars** [comment]
I think I have a vague idea of what is happening, since I was reading the Telnet Terminal-Type Option RFC last night and wondered if something like this might be a problem. I'll try something out to see if I can work around this.

**Comment by racingmars** [comment]
Playing around with this, I think the current behavior is okay... can you watch this video and see if you are getting the same behavior and if you agree that it is acceptable? Or are there situations where this isn't working the way you expect? https://youtu.be/1lPAywiWXcA

**Comment by moshix** [comment]
The video is private. Can't see it. 

I think it's a bug in Vista3270. x3270 handles size correctly. Let me play with it a bit more

thanks a lot!

**Comment by racingmars** [comment]
Oh -- sorry about that, video link should work now if you want to see if that matches the behavior you're seeing with Vista

**Comment by moshix** [comment]
Ok, thanks saw it now. 

No, that's not the behavior of my Vista3270. My vista switches to Mod2 and stays Mod2. And it often causes proxy3270 to crash also. 

Maybe try to stress proxy3270 by connecting with a very large terminal, like 6linesx90 wide and see it this causes proxy3270 to crash on your side. 

thanks a lot!
