### ISSUE TITLE
add logging to file ( to avoid doing a tee )

### ISSUE THREAD

**Issue by moshix** [racingmars/proxy3270#7]
In my branch I do something like this:

 // Run the accept loop in a goroutine so we can wait on the quit signal
        go func() {
                 conn, err := ln.Accept()
                        if err != nil {
                                log.Error().Err(err).Msg("Couldn't accept connection")
                        }
                        log.Info().Msgf("New connection from %s", conn.RemoteAddr())

                        f, err := os.OpenFile("./connections.log",
                                os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0666)
                        if err != nil {
                               log.Info().Msgf("Error in opening connections.log")      
                        }
                        defer f.Close()
                        ip:= conn.RemoteAddr().String()
                        if _, err := f.WriteString(">" + ip); err != nil {
                                log.Info().Msgf("General error writing to connections.log")
                        }
                        
                        go handle(conn, *telnetTimeout)
                }
        }()
   
Would you consider adding that?

thanks

M

**Comment by racingmars** [comment]
Done. Added a "-log" command line parameter to append the log to a file, too. Also added more client activity logging -- the initial connection, which host they choose to proxy through to, and when the client session ends.
