### ISSUE TITLE
Cannot build on z/Ubuntu 18.04

### ISSUE THREAD

**Issue by moshix** [racingmars/proxy3270#8]
I am using Golang 1.15 on Ubuntu 18.04 on a z15 instruction-level machine and I get this during build:

root@zubuntu:~/proxy3270# go build
go: github.com/racingmars/go3270@v0.0.0-20201227093120-f01cf72d6de3: Get "https://proxy.golang.org/github.com/racingmars/go3270/@v/v0.0.0-20201227093120-f01cf72d6de3.mod": net/http: TLS handshake timeout

**Comment by moshix** [comment]
On RHEL 7 on a z114, I get this:

[root@selxm1 proxy3270]# go build
go: downloading github.com/rs/zerolog v1.20.0
go: downloading github.com/racingmars/go3270 v0.0.0-20201227093120-f01cf72d6de3
# runtime
/usr/local/go/src/runtime/mgclarge.go:320:6: s.scavenged undefined (type *mspan has no field or method scavenged)
/usr/local/go/src/runtime/mgclarge.go:323:6: s.hugePages undefined (type *mspan has no field or method hugePages)
/usr/local/go/src/runtime/mgclarge.go:390:13: s.hugePages undefined (type *mspan has no field or method hugePages)
/usr/local/go/src/runtime/mgclarge.go:391:16: s.scavenged undefined (type *mspan has no field or method scavenged)
/usr/local/go/src/runtime/mgclarge.go:396:9: mheap_.free undefined (type mheap has no field or method free)
/usr/local/go/src/runtime/mgclarge.go:398:7: s.scavenged undefined (type *mspan has no field or method scavenged)
/usr/local/go/src/runtime/mgclarge.go:399:9: mheap_.free undefined (type mheap has no field or method free)
/usr/local/go/src/runtime/signal_unix.go:525:5: crashing redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal_sighandler.go:15:5
/usr/local/go/src/runtime/signal_unix.go:530:5: testSigtrap redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal_sighandler.go:20:5
/usr/local/go/src/runtime/signal_unix.go:544:6: sighandler redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal_sighandler.go:33:69
/usr/local/go/src/runtime/mgclarge.go:399:9: too many errors
[root@selxm1 proxy3270]#

**Comment by racingmars** [comment]
Those look like problems with the Go tools in the environment. The first seems to be a network problem accessing the Go package cache server, and the second is...I don't know, but some failure in the Go compiler itself. I don't think there's anything I can do about either.

I *can* cleanly cross-compile the project from Linux/amd64, though. e.g. on my system if I run `GOOS=linux GOARCH=s390x go build`, the build succeeds. If you try that and copy the proxy3270 executable over to zLinux, does it work? If so... then I think the other errors are probably problems in Go that you'd want to report to the Go project itself.

(Of course... now you're making me want to spend the time to get a Linux distro up and running on my zD&T ;-) )

**Comment by moshix** [comment]
yes, building with crosscompilation works, but strangely with Go 1.13 I can't compile this on zLinux directly. thanks
